version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"  # Expose Flask on port 5001
    environment:
      - FLASK_APP=run:app
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)
    depends_on:
      - db
    volumes:
      - ./backend:/app  # Ensure this path is correct for your Flask app
    command: flask run --host=0.0.0.0


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Map PostgreSQL port to a different host port
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
