version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
