import { Inter } from 'next/font/google';
import Script from 'next/script';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-9DE8VT28S2"
        ></Script>
        <Script id="google-analytics">
          {`
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments);}
          gtag('js', new Date()); gtag('config', 'G-9DE8VT28S2');
          `}
        </Script>
      </head>
      <body
        className={`${inter.className} bg-gradient-to-br from-cyan-50 via-slate-100 to-teal-50`}
      >
        {children}
      </body>
    </html>
  );
}
