"""Add user_id to complaint table

Revision ID: 5aafe88e3fbb
Revises: 
Create Date: 2024-08-18 17:57:36.660231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5aafe88e3fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'complaint', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    op.drop_column('complaint', 'user_id')
    # ### end Alembic commands ###
